pr: none
trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
- group: vg-azure-sample

steps:
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: "$(AZURE_RM_SVC_CONNECTION)"
      action: "Create Or Update Resource Group"
      resourceGroupName: "$(RESOURCE_GROUP)"
      location: $(LOCATION)
      templateLocation: "Linked artifact"
      csmFile: "$(Build.SourcesDirectory)/environment_setup/azuredeploy.json"
      csmParametersFile: "$(Build.SourcesDirectory)/environment_setup/azuredeploy.parameters.json"
      deploymentMode: "Incremental"
    env:
      TENANT_ID: $(TENANT_ID)
    displayName: "Deploy Azure ML resources"

