pr: none
trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
- group: vg-azure-sample

steps:
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: "$(AZURE_RM_SVC_CONNECTION)"
      action: "Create Or Update Resource Group"
      resourceGroupName: "$(RESOURCE_GROUP)"
      location: $(LOCATION)
      templateLocation: "Linked artifact"
      csmFile: "$(Build.SourcesDirectory)/environment_setup/azuredeploy.json"
      csmParametersFile: "$(Build.SourcesDirectory)/environment_setup/azuredeploy.parameters.json"
      overrideParameters: "-basename $(BASE_NAME) -location $(LOCATION)"
      deploymentMode: "Incremental"
    displayName: "Deploy Azure ML resources"

